### ISSUE TITLE
Trying to run in Docker Compose

### ISSUE THREAD

**Issue by trentonsnyder** [hiett/serverless-redis-http#3]
I started working to get this running in docker-compose and ran into an error when running `up`. I `exec` into the container and it looks like the file is mounted in the correct place in `app/srh-config/tokens.json`

I thought it would be cool to get compose instructions in the readme or at least help to figure out how to support it. I might just have some network config wrong. I know there's a lot of things that could be wrong with my set up and not necessarily this repo. But any tips would be appreciated. 

Error:
```qemu: uncaught target signal 11 (Segmentation fault) - core dumped```

tokens.json
```
{
  "development-token": {
    "srh_id": "some_unique_identifier",
    "connection_string": "redis:6379",
    "max_connections": 3
  }
}
```

docker-compose.yaml
```
  redis:
    image: redis
    ports:
      - '6379:6379'
    expose:
      - 6379
    volumes:
      - ./packages/must-stash/volume:/data
  serverless-redis-http:
    ports:
      - '8079:80'
    image: 'hiett/serverless-redis-http:latest'
    volumes:
      - ./packages/must-stash/local-config/tokens.json:/app/srh-config/tokens.json
```

I then cloned the repo and built the image ran `up` pointed to my local image and wasn't getting the same error. It seemed to stay up ok. Then I tried hitting `http://localhost:8079` with `'@upstash/redis'` doing a `set` and `hset` and got an Elixir error. So, I got a little closer.

<img width="1155" alt="Screen Shot 2022-10-04 at 9 12 07 AM" src="https://user-images.githubusercontent.com/17258002/193857304-385a510c-65e0-41e1-b8bd-6cc5f7a21f14.png">

**Comment by hiett** [comment]
Hey! Thanks for reaching out. Reading that error, it looks like it's unable to pass your connection_string as a URI. From the tokens.json you provided, you've just got `redis:6379` - could you try formatting it as a URI (eg `redis://redis:6379`) and let me know if that fixes it?

**Comment by hiett** [comment]
Regarding the segmentation fault, are you by any chance running an M1 Mac? From some brief googling it seems to be an issue commonly associated with that (I compiled this on an x64 mac).

I can look into some solutions online and get some CI up and running so it compiles via that, rather than me just doing it on my Macbook :)

**Comment by trentonsnyder** [comment]
> are you by any chance running an M1 Mac?

Ah yes I am. I should have mentioned that.

> could you try formatting it as a URI (eg redis://redis:6379) 

Yes! this works. So now when I use a locally built image of this repo I'm able to communicate with the `redis` in docker using `upstash/redis`.

eg
```
import { Redis } from '@upstash/redis/with-fetch'

const redis = new Redis({
  url: 'http://localhost:8079',
  token: 'development-token'
})

async function go() {
  const what = await redis.get('abra')
  console.log({ what })
}

go()
```
<img width="254" alt="it-works" src="https://user-images.githubusercontent.com/17258002/194184931-6445f90b-03d1-487a-b9cf-6c092b7fcd07.png">

**Comment by hiett** [comment]
Fantastic, glad it's working.

From the research I've done then, it seems that the issue is that I'm not also distributing an ARM-based Docker container to DockerHub. This seems like a simple fix on my end. I'll get some CI setup in a bit that will compile and push both. Then should be good to go!

**Comment by hiett** [comment]
Hey @trentonsnyder!

I've just pushed a new docker image to DockerHub under the tag `0.0.4-alpha`, that has both an amd64 build and an arm64 build.

Would you be able to test that out in your Docker Compose to see if it fixes the segmentation fault?

```yaml
serverless-redis-http:
  image: hiett/serverless-redis-http:0.0.4-alpha
  ... etc ...
```

https://hub.docker.com/layers/hiett/serverless-redis-http/0.0.4-alpha/images/sha256-ae41dba9f6ea1d947cb93618918935459b989e09e50016d057f72ede331d1e40?context=explore
