### ISSUE TITLE
SRH: Endpoint not found

### ISSUE THREAD

**Issue by vignesh-gupta** [hiett/serverless-redis-http#37]
I'm setting up local env instead of cloud redis.

Docker compose:
```
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  serverless-redis-http:
    ports:
      - "8079:80"
    image: hiett/serverless-redis-http:latest
    environment:
      SRH_MODE: env
      SRH_TOKEN: example_token
      SRH_CONNECTION_STRING: "redis://redis:6379" # Using `redis` hostname since they're in the same Docker network.
```

Output from http://localhost:8079/set/foo/bar
```
{
"error": "SRH: Endpoint not found. SRH might not support this feature yet."
}
```
